name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        cd TiksiHehku
        npm install

    - name: Build project
      run: |
        cd TiksiHehku
        npm run build

    - name: Deploy to Firebase
      run: |
        cd TiksiHehku
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
